name: CobblemonPlacholder
version: 0.0.2
main: ca.skynetcloud.cobblemonplaceholder.Cobblemonplaceholder
api-version: 1.19
depend: [ PlaceholderAPI ]
authors: [ SkyNetCloud ]
description: A simple utility to link your PAPI with Cobblemon!